-- Disable foreign key checks
SET FOREIGN_KEY_CHECKS = 0;

-- Generate and execute commands to drop foreign key constraints
SELECT CONCAT('ALTER TABLE `', TABLE_NAME, '` DROP FOREIGN KEY `', CONSTRAINT_NAME, '`;')
FROM information_schema.KEY_COLUMN_USAGE
WHERE CONSTRAINT_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME IS NOT NULL;

ALTER TABLE mhl_contacts
ADD CONSTRAINT 
FOREIGN KEY (supplier_ID) REFERENCES mhl_suppliers(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_contacts
ADD CONSTRAINT 
FOREIGN KEY (department) REFERENCES mhl_departments(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_suppliers
ADD CONSTRAINT 
FOREIGN KEY (membertype) REFERENCES mhl_membertypes(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_suppliers
ADD CONSTRAINT 
FOREIGN KEY (city_ID) REFERENCES mhl_cities(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_suppliers
ADD CONSTRAINT 
FOREIGN KEY (p_city_ID) REFERENCES mhl_cities(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_suppliers
ADD CONSTRAINT 
FOREIGN KEY (company) REFERENCES mhl_companies(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_suppliers
ADD CONSTRAINT 
FOREIGN KEY (postcode) REFERENCES pc_lat_long(pc6)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_suppliers
ADD CONSTRAINT 
FOREIGN KEY (p_postcode) REFERENCES pc_lat_long(pc6)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_cities
ADD CONSTRAINT
FOREIGN KEY (commune_id) REFERENCES mhl_communes(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_communes
ADD CONSTRAINT
FOREIGN KEY (district_id) REFERENCES mhl_districts(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_districts
ADD CONSTRAINT
FOREIGN KEY (country_ID) REFERENCES mhl_countries(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_properties
ADD CONSTRAINT
FOREIGN KEY (supplier_ID) REFERENCES mhl_suppliers(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_properties
ADD CONSTRAINT
FOREIGN KEY (propertytype_ID) REFERENCES mhl_propertytypes(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_yn_properties
ADD CONSTRAINT
FOREIGN KEY (supplier_ID) REFERENCES mhl_suppliers(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_yn_properties
ADD CONSTRAINT
FOREIGN KEY (propertytype_ID) REFERENCES mhl_propertytypes(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_detaildefs
ADD CONSTRAINT
FOREIGN KEY (propertytype_ID) REFERENCES mhl_propertytypes(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_detaildefs
ADD CONSTRAINT
FOREIGN KEY (group_ID) REFERENCES mhl_detailgroups(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_suppliers_mhl_rubriek_view
ADD CONSTRAINT
FOREIGN KEY (mhl_suppliers_ID) REFERENCES mhl_suppliers(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE mhl_suppliers_mhl_rubriek_view
ADD CONSTRAINT
FOREIGN KEY (mhl_rubriek_view_ID) REFERENCES mhl_rubrieken(id)
ON DELETE RESTRICT
ON UPDATE RESTRICT;


-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;
